// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package helloworld

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoMicroClient is the client API for GoMicro service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoMicroClient interface {
	SayHello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRes, error)
}

type goMicroClient struct {
	cc grpc.ClientConnInterface
}

func NewGoMicroClient(cc grpc.ClientConnInterface) GoMicroClient {
	return &goMicroClient{cc}
}

func (c *goMicroClient) SayHello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRes, error) {
	out := new(HelloRes)
	err := c.cc.Invoke(ctx, "/helloworld.GoMicro/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoMicroServer is the server API for GoMicro service.
// All implementations must embed UnimplementedGoMicroServer
// for forward compatibility
type GoMicroServer interface {
	SayHello(context.Context, *HelloReq) (*HelloRes, error)
	mustEmbedUnimplementedGoMicroServer()
}

// UnimplementedGoMicroServer must be embedded to have forward compatible implementations.
type UnimplementedGoMicroServer struct {
}

func (UnimplementedGoMicroServer) SayHello(context.Context, *HelloReq) (*HelloRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGoMicroServer) mustEmbedUnimplementedGoMicroServer() {}

// UnsafeGoMicroServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoMicroServer will
// result in compilation errors.
type UnsafeGoMicroServer interface {
	mustEmbedUnimplementedGoMicroServer()
}

func RegisterGoMicroServer(s grpc.ServiceRegistrar, srv GoMicroServer) {
	s.RegisterService(&GoMicro_ServiceDesc, srv)
}

func _GoMicro_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoMicroServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.GoMicro/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoMicroServer).SayHello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GoMicro_ServiceDesc is the grpc.ServiceDesc for GoMicro service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoMicro_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.GoMicro",
	HandlerType: (*GoMicroServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GoMicro_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
