apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-p2cserver
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-p2cserver
  template:
    metadata:
      labels:
        app: test-p2cserver
      annotations:
        field.mops.io/appName: test-p2cserver
        prometheus.io/port: "9003"
        prometheus.io/scrape: "true"        
    spec:
      containers:
        - env:
            - name: EGO_CONFIG_PATH
              value: config/dev.toml
            - name: EGO_LOG_WRITER
              value: stderr
          image: reg.smvm.cn/cicd/shimo-saas/p2cserver:0.16
          imagePullPolicy: Always
          name: test-p2cserver
          ports:
            - containerPort: 9001
              name: 9001tcp
              protocol: TCP
            - containerPort: 9003
              name: 9003tcp
              protocol: TCP
      imagePullSecrets:
        - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: test-p2cserver
  namespace: default
spec:
  ports:
    - name: test-p2cserver-9002-9002
      port: 9002
      protocol: TCP
      targetPort: 9002
    - name: test-p2cserver-9001-9001
      port: 9001
      protocol: TCP
      targetPort: 9001
    - name: test-p2cserver-9003-9003
      port: 9003
      protocol: TCP
      targetPort: 9003
  selector:
    app: test-p2cserver
  type: ClusterIP
